# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statistics.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtWidgets, uic
from user import Users
import menu
import threading

class Statistics_Window(QtWidgets.QMainWindow):
     def __init__(self, user):
        self.user = user
        super(Statistics_Window, self).__init__()
        uic.loadUi('Ui/statistics.ui', self)

        self.quitbutton.clicked.connect(self.backk)
        

        self.show()
     def backk(self):
        
        self.cams = menu.Menuscreen_window(self.user)
        self.cams.show()
        self.close()